### ISSUE TITLE
Breaking changes plan for v2

### ISSUE THREAD

**Issue by svartalf** [actions-rs/toolchain#16]
[ ] Make `override: true` input by default
[ ] Make `profile: minimal` input by default

**Comment by jhpratt** [comment]
Couldn't a `targets` input be provided, explicitly overriding `targef`? That would be back-compatible. Alternatively, it could be additive.

**Comment by svartalf** [comment]
@jhpratt yeah, it is pretty much possible, but this feature does not look that important, so it is easier to postpone it till the breaking release.

Until then, simple `run` step can be used as a workaround, as this Action guarantees that there always will be a `rustup` in `PATH`:

```yaml
- uses: actions-rs/toolchain@v1
  with: // skipped for clarity
- run: rustup target add my-new-target
```
