### ISSUE TITLE
Support locking to exact component versions

### ISSUE THREAD

**Issue by richard-viney** [actions-rs/toolchain#161]
Is it possible to lock the versions of components that are installed? I'm running into issues with clippy where a newer version of it gets installed and recently-added rules cause the workflow to fail due to clippy warnings that didn't previously exist. If we could lock the version of clippy somehow then this wouldn't happen, CI runs would be more deterministic, and users could upgrade clippy at their own pace.

The workflow this problem occurred on, which it seems doesn't manage to lock the clippy version, but does specify the Rust version, was setup like this:

```yaml
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0
          components: rustfmt, clippy
      - name: Install dependencies
        run: cargo fetch
      - name: Run linter
        run: cargo clippy --release -- --deny warnings
```
