### ISSUE TITLE
Add support for multiple targets

### ISSUE THREAD

**Issue by haata** [actions-rs/toolchain#165]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

I have a larger embedded project that supports multiple boards (each with their own crate).
The build process uses cargo-make and supports multiple targets during a top-level build.

Currently I need the following targets for a successful build:
- thumbv6m-none-eabi
- thumbv7em-none-eabi
- thumbv7em-none-eabihf

Along with x86_64-unknown-linux-gnu for unit tests.

It would be useful to specify all the needed targets as a list, just like the components field.

## Workflow example

```yaml
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          targets: thumbv6m-none-eabi, thumbv7em-none-eabi, thumbv7em-none-eabihf
          override: true
```

I have no preference of target vs. targets. targets is probably easier for backward compatibility.
