### ISSUE TITLE
Support forcing self update of rustup?

### ISSUE THREAD

**Issue by matklad** [actions-rs/toolchain#170]
In rust-analyzer's CI, we are seeing rustup running out of memory frequently:

https://github.com/rust-analyzer/rust-analyzer/runs/2655689554#step:4:31

I think this should be fixed with the most recent rustup: https://blog.rust-lang.org/2021/05/17/Rustup-1.24.2.html

So I think that I'd be able to fix rust-analyzer's CI if I had something like this, to force self-update before toolchain download:

```yaml
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        self-update: true
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, rust-src
```
