### ISSUE TITLE
use minimal supported rust version `rust-version` from Cargo.toml

### ISSUE THREAD

**Issue by EdJoPaTo** [actions-rs/toolchain#206]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

Rust 1.56 added the [Cargo manifest key `rust-version`](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-rust-version-field) to indicate the minimal supported rust version (MSRV).

It would be nice to only configure this only in a single location and use it automatically from ci.

## Workflow example

The big question is probably how this would be useful as a config.

Adding a special key for this might be easier to understand but is error prone and has many unclear states.
```yaml
      - uses: actions-rs/toolchain@v1
        with:
          # Dont use the toolchain key
          # toolchain: nightly
          override: true
          msrv: true
```

providing a special value to the toolchain value is also not as nice as I would like it to be.
```yaml
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: rust-version
          override: true
```
