### ISSUE TITLE
Project unmaintained

### ISSUE THREAD

**Issue by pickfire** [actions-rs/toolchain#216]
@svartalf I believe the project needs another maintainer since the issues and pull requests have no one to tend to them. Probably would be good if there are other people to help maintain actions-rs, like outdated template (`v2` instead of `v3`).

Not sure if author will reply here, so I will email him.

**Comment by smallstepman** [comment]
I tried contacting @svartalf via email from his GH profile on June 16th, however, haven't heard from him back.

Given his last contribution to `actions-rs` was in Nov 2020, I think the best course of action would be to fork the entire organization.  

Personally, I'd love to see this go under the https://github.com/rust-unofficial umbrella since such a move makes it less likely for the project to go stale again, or even (ideally) https://github.com/orgs/rust-lang/repositories?q=action ... Perhaps we could try to ping someone from `rust-lang`, I saw @steveklabnik showing interest in [one of the PRs here some time ago](https://github.com/actions-rs/toolchain/pull/166#issuecomment-953312606) - maybe you could help us get the ball rolling? Having GHActions run officially by the organization mitigates a bunch of security risks...

Otherwise, we can create a new organization. Not gonna lie, `actions-rs` is I think a fantastic name, but maybe we can come up with something as good.

**Comment by pickfire** [comment]
If any, I think https://github.com/actions/setup-rust is the best since most other popular languages are there.

**Comment by smallstepman** [comment]
that would also be fantastic! do you know how to get in?

**Comment by pickfire** [comment]
Not sure, but seemed like they stopped accepting new workflows. https://github.com/actions/starter-workflows/issues/631

**Comment by steveklabnik** [comment]
I am no longer affiliated with the Rust Project, so if you're looking for an official fork, I can't be of help, sadly.

> If any, I think https://github.com/actions/setup-rust is the best since most other popular languages are there.

By the way, this 404s for me...

**Comment by pickfire** [comment]
> By the way, this 404s for me...

Yes, it's 404. I suggested that but don't have access to actions organization.

**Comment by smallstepman** [comment]
Fork? Or we try other ideas?

**Comment by dralley** [comment]
Let's not fork until we have an idea of where it would go at the very least.  Meaning an official organization if at all possible.

It is also possible that @svartalf may eventually respond and be willing to add new maintainers to the existing organization.

**Comment by dralley** [comment]
> It is also possible that @svartalf may eventually respond and be willing to add new maintainers to the existing organization.

Such as perhaps @dtolnay?  https://github.com/dtolnay/rust-toolchain

**Comment by dtolnay** [comment]
Nope, I am not interested in being added as a maintainer.

**Comment by sondr3** [comment]
From the reddit thread and here it looks to me like the most likely way forward is either to essentially fork the entire organization or start anew but make sure that the bus factor is greater than one. Would it be possible to perhaps create an action in [rust-lang-nursery](https://github.com/rust-lang-nursery) with the possibility of moving it to the `rust-lang` repo proper like [haskell/actions](http://github.com/haskell/actions) / [deno-land/setup-deno](https://github.com/denoland/setup-deno)? I realize that this requires a fair amount of trust, but it is in my opinion the best option. 

As an aside, something I really like with for example `setup-node` is that it has built-in caching so no messing about with `action/cache`, so maybe include @Swatinem in the conversation since he has written a _great_ Rust caching action.

**Comment by Swatinem** [comment]
To be fair, I think just `run: rustup install stable` and variations of that one, and similarly `run: cargo test` is way simpler than something based on an action.

I believe for the toolchain, [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) may do better caching for toolchains that are not directly installed on the runners, though I haven’t used that myself so far.

Also, thanks for your kind words ;-)

**Comment by smallstepman** [comment]
@Swatinem do you know a way to install rust_version & components & targets comming fom `rust-toolchain.tom` in one command? Not sure if `rustup show` doesn't do that... (which is quite bizzare given the name of the command - https://github.com/rust-lang/rustup/issues/1397) 

For my usecase, this whole Action would no longer had any use if this would land:
- https://github.com/rust-lang/rustup/issues/2686

**Comment by Swatinem** [comment]
I’m not really familiar with `rust-toolchain.toml` and how to best use that. For the projects I help maintain, we test against our MSRV, stable and beta, and have no requirements for more specific versions.

I would imagine just updating your `rustup` invocation for your CI job alongside `rust-toolchain.toml` updates would suffice, but like I said I’m not really familiar with any of this.

**Comment by jonasbb** [comment]
The dtolnay/rust-toolchain action felt a bit too bare bones to me, so I created https://github.com/actions-rust-lang/setup-rust-toolchain based on it. It does some extra steps on top like disabling incremental compilation for faster building from scratch (`CARGO_INCREMENTAL=0`) and sets up [problem matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) for cargo and rustfmt.

**Comment by pickfire** [comment]
@jonasbb instead of doing that, why not just send a pull request to dtolnay repository? Also, it seemed to use `CARGO_INCREMENTAL=0` after https://github.com/dtolnay/rust-toolchain/pull/27

**Comment by jonasbb** [comment]
@pickfire There are some maintenance concerns which make me convinced a separate project is more beneficial. However, this issue is not the place to discuss these concerns.

**Comment by Bromeon** [comment]
If you don't need lots of customizability, this works quite well for installation and caching of dependencies:
```yaml
# File .github/composite/rust/action.yml

name: rust
description: "Install Rust toolchain, with caching"

inputs:
  rust:
    required: false
    description: "Rust toolchain, e.g. 'stable' or 'nightly'"
    default: stable
  cache-key:
    required: false
    description: "Extra key to resolve cache"
    default: ''

runs:
  using: "composite"
  steps:
    - name: "Install Rust"
      run: |
        rustup toolchain install ${{ inputs.rust }} --profile minimal --no-self-update
        rustup default ${{ inputs.rust }}
      shell: bash

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV
        
        rustc --version --verbose
      shell: bash
```
