### ISSUE TITLE
Node.JS 12 deprecation on GitHub Actions

### ISSUE THREAD

**Issue by caizixian** [actions-rs/toolchain#219]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description
GitHub Action hosted runner is reporting the following warning.

```console
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions-rs/toolchain
```

## Workflow code

```yaml
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
```
 
## Action output
See above.

## Expected behavior
Migrate actions-rs/toolchain to Node.JS 16.

## Additional context

N/A.

**Comment by Bromeon** [comment]
We might wait a long time here, given that this project has been unmaintained for almost 2 years: #216

**Comment by elibroftw** [comment]
Non interactive install for anyone who only needs stable rust.

```yaml
      - name: Install Rust (Stable)
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
```

**Comment by dallin-ukralabs** [comment]
Unfortunate the project seems abandoned, was using it daily.

**Comment by Finomnis** [comment]
As it's rude to make requests without giving back, I tipped a little to encourage the change :) https://www.buymeacoffee.com/svartalf/c/4561094
Other people, feel free to join if you benefit from this tool.

**Comment by mondeja** [comment]
In most cases you don't need this action at all:

```yml
test:
  strategy:
    matrix:
      rust-toolchain:
        - stable
        - nightly
  steps:
    - name: Setup Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        rustup default ${{ matrix.rust-toolchain }}
```

**Comment by a1ecbr0wn** [comment]
Do you think this guy is dead?  Is there a way to add other people to the project to maintain it without him given that he has been MIA for 2+ years?  This action will cease to work in a couple of months and that would be a real shame given it's wide use.

**Comment by Ujang360** [comment]
@svartalf are you OK?

**Comment by milesj** [comment]
Now that Node 12 is going to start breaking, and this action is dead, I've created a new one: https://github.com/moonrepo/setup-rust

**Comment by mgeisler** [comment]
> Now that Node 12 is going to start breaking, and this action is dead, I've created a new one: https://github.com/moonrepo/setup-rust

May I ask what this action (and your new action) is for when the [GitHub runners already include `rustup`](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools)?

**Comment by milesj** [comment]
@mgeisler Just look at the readme.

**Comment by mgeisler** [comment]
> @mgeisler Just look at the readme.

Thanks, I was expecting it to simply replace this action, but I see now that it also includes support for caching and installing binaries. That will allow me to further simplify my jobs, thanks.

**Comment by istellino-chub** [comment]
How can I replace this one?
```
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true
```

**Comment by Finomnis** [comment]
> How can I replace this one?
> 
> ```
>         name: Install Rust
>         uses: actions-rs/toolchain@v1
>         with:
>           toolchain: stable
>           target: x86_64-unknown-linux-musl
>           default: true
> ```

@istellino-chub 

```
         name: Install Rust
         uses: dtolnay/rust-toolchain@stable
         with:
           targets: x86_64-unknown-linux-musl
```

More info [here](https://github.com/dtolnay/rust-toolchain).

**Comment by istellino-chub** [comment]
> 

thanks @Finomnis does that install rust? I though that it install the toolchain

**Comment by Finomnis** [comment]
@istellino-chub What's the difference between 'Rust' and the 'Rust toolchain'?

What `dtolnay/rust-toolchain` installs is rustc, cargo, and so on. Exactly what `actions-rs/toolchain` did as well.

**Comment by istellino-chub** [comment]
> @istellino-chub What's the difference between 'Rust' and the 'Rust toolchain'?
> 
> What `dtolnay/rust-toolchain` installs is rustc, cargo, and so on. Exactly what `actions-rs/toolchain` did as well.

@Finomnis And what about the `profile` and `override` option
```
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
```
