### ISSUE TITLE
Requesting toolchain version 1.70 installs 1.7.0

### ISSUE THREAD

**Issue by ydirson** [actions-rs/toolchain#230]
## Description

After switching my action from install toolchain 1.66 to 1.70, what I actually get is 1.7.0 (and surprisingly he build fails).
As a workaround requesting 1.70.0 works, but it's obviously not good, in case a 1.70.1 comes out.

## Workflow code

https://github.com/xcp-ng/xcp-metrics/commit/51756943bb633ece8c5ebb398f2dad65d189308d

```
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
-        toolchain: 1.66
+        toolchain: 1.70
        override: true
```

## Action output

https://github.com/xcp-ng/xcp-metrics/actions/runs/6377565635/job/17306468710

```
Run actions-rs/toolchain@v1
/home/runner/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.72.1 (d5c2e9c34 2023-09-13)
/home/runner/.cargo/bin/rustup toolchain install 1.7
info: syncing channel updates for '1.7.0-x86_64-unknown-linux-gnu'
```
