### ISSUE TITLE
Documentation claims `toolchain: stable` is default, but it is not.

### ISSUE THREAD

**Issue by jwalton** [actions-rs/toolchain#231]
## Description

The README.md says that the "stable" toolchain is the default:

![image](https://github.com/actions-rs/toolchain/assets/1771003/8b62c12e-d81d-4f4f-96c5-892212312f0d)

But if you don't specify a toolchain, you get:

```
Error: toolchain input was not given and repository does not have a rust-toolchain file
```

(See https://github.com/jwalton/rust-tokio-task-tracker/actions/runs/6436035135/job/17478566687).

## Workflow code

```yaml
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - run: cargo test
      - run: cargo clippy
```
 
## Action output

```
   with:
    default: false
    override: false
Error: toolchain input was not given and repository does not have a rust-toolchain file
```

## Expected behavior

Should default to `toolchain: default`.
