### ISSUE TITLE
Getting `rust: command not found` after install

### ISSUE THREAD

**Issue by lynncyrin** [actions-rs/toolchain#36]
## To reproduce

If you run the following github actions config

```yaml
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: setup rust
        uses: actions-rs/toolchain@v1

      - name: run tests
        run: rust --version
```

## Observed behavior

You'll get `rust: command not found`

## Expected behavior

Whereas you would expect `rust v1.40.X ...`

## Additional context

My build can be viewed here => https://github.com/lynncyrin/algo-zone/runs/365065973
