### ISSUE TITLE
Output the version of the installed toolchain

### ISSUE THREAD

**Issue by pietroalbini** [actions-rs/toolchain#46]
It'd be nice if the action added the output of `rustc --version` (either verbatim or slightly tweaked) as an output value of the step.

For example, it might be desiderable to have separate caches based on the rustc version, so when the nightly updates a new cache is created:

```yaml
- uses: actions-rs/toolchain@v1
  id: rustc
  with:
    toolchain: nightly

- uses: actions/cache
  with:
    path: target
    key: ${{ runner.os }}-${{ steps.rustc.outputs.version }}
```
