### ISSUE TITLE
Installing a specific toolchain depending on OS

### ISSUE THREAD

**Issue by casey** [actions-rs/toolchain#48]
I needed to install a specific toolchain depending on which OS the job was running under, and my solution involved a bunch of repetition, so I'm wondering if there's a better way.

The only thing that differs between the various `Install` steps is the `if` conditional and the toolchain `target`:

```
name: Main

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Install
      if: matrix.os == 'ubuntu-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        profile: minimal
        components: clippy, rustfmt
        override: true
    - name: Install
      if: matrix.os == 'windows-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        profile: minimal
        components: clippy, rustfmt
        override: true
    - name: Install
      if: matrix.os == 'macos-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        profile: minimal
        components: clippy, rustfmt
        override: true
```
