### ISSUE TITLE
[question] How to resolve problem with rustup that can't find nightly with miri?

### ISSUE THREAD

**Issue by WaffleLapkin** [actions-rs/toolchain#70]
I have a rust project with a lot of unsafe code and I want to run `cargo miri test` in CI to be sure everything is ok. 

I've added `miri` to the components list:
[`components: rustfmt, clippy, miri`](https://github.com/WaffleLapkin/arraylib/blob/master/.github/workflows/ci.yml#L32) 
and added miri setup/test actions:
```yaml
      - name: miri setup
        uses: actions-rs/cargo@v1
        if: matrix.rust == 'nightly'
        with:
          command: miri
          args: setup

      - name: miri test
        uses: actions-rs/cargo@v1
        if: matrix.rust == 'nightly'
        with:
          command: miri
          args: test
```

This worked for me, but today CI has broken up because `rustup` couldn't find nightly with `miri`: [ci run](https://github.com/WaffleLapkin/arraylib/pull/16/checks?check_run_id=552697838)

How can I resolve the issue?
