### ISSUE TITLE
Supply specific list of components to install

### ISSUE THREAD

**Issue by nagisa** [actions-rs/toolchain#71]
# Motivation

I’m trying to make a CI that tests `x86_64-unknown-openbsd` target. There is no rust-std component for this target so I thought I’d just get actions to build libstd in the first place (via e.g. `-Zbuild-std`).

Alas, I’m not seeing how to disable `rust-std` component with this workflow, so I’ll probably have to write one myself...

## Workflow example

```yaml
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: x86_64-unknown-openbsd
            profile: minimal
            default: true
            components: rust-src
```
